version: "3"
services:
    postgres:
        image: postgres:latest
        container_name: postgres1
        ports:
            - "6500:5432"
        volumes:
            - progresDB:/var/lib/postgresql/data
        env_file:
            - ./.env.local
    pgAdmin:
        image: dpage/pgadmin4
        container_name: pgAdmin1
        env_file:
            - ./.env.local
        ports:
            - "5050:80"
    redis:
        image: redis:latest
        restart: always
        ports:
        - "6379:6379"
        volumes:
        - /path/to/local/d–∞ta:/root/redis
        - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
        - REDIS_PASSWORD=my-password
        - REDIS_PORT=6379
        - REDIS_DATABASES=16

volumes:
    progresDB:
